Update sticker sheet
uswds/uswds-for-designers pull request #42
Opened 2017-02-17 21:31 UTC by bradnunnally

Updated the sticker sheets to include the new header pattern and to correct a "design bug" that was present in the illustrator file where the body copy in the table component was the wrong font size. 

Ready for review @shawnbot and @juliaelman

2017-02-21 18:21 UTC, juliasolorzano reviewed
@bradnunnally nice work! 🎉 Here are a few questions and comments I have, broken out into each file to make it easier to follow:

**ALL**
- Please add the extended header with no mega menu.
- Please add the basic header with the mega menu.
- The extended header with the mega menu should have the top level item highlighted.
- Should we call out the show/hide functionality of the search box in the extended header in the file somehow?
- Please change the font size in the table component from 16px to 17px.

**Sketch, PDF**
- The search icon for the extended header is offset. See the screenshot below for reference: 
![screen shot 2017-02-21 at 1 08 34 pm](https://cloud.githubusercontent.com/assets/955558/23178049/fb3dd8c2-f836-11e6-8a1e-20fc0cc006b7.png)

**Omnigraffle**
- Should we replace the v.8 with v.1.0? Not sure how to get this naming convention in sync with our 1.0 release.

2017-02-21 19:18 UTC, bradnunnally commented
Sketch file updated. Going to sync the branch then move on to the AI file.

2017-02-22 17:06 UTC, bradnunnally commented
@juliaelman The files have all been updated based on your feedback.

2017-02-22 21:21 UTC, juliaelman commented
Putting some more notes in here to keep track of all the things:

- Please change the font size in the table component from 16px to 17px in all of the files.
- The underline is off a bit in the mega menu selected tab indicator, see screenshot below.
- Remove `Omnigraffle` from PDF filename

2017-02-23 16:30 UTC, bradnunnally commented
Alright! 🎉  The sticker sheets have been updated, file names have been updated, and the readme file has been updated. 

I'm 99% sure everything is good to start merging this PR. 

/cc @juliaelman @shawnbot

2017-02-23 17:27 UTC, juliasolorzano requested changes
I think we are almost there!

- Are we going to have an EPS file too or just the EPS preview? When I pulled down the latest change set it only had the EPS preview file.

2017-02-23 17:27 UTC, juliaelman commented on README.md
> +For the 1.0 release, the following file types are available for your use:
I think we can remove `For the 1.0 release,` from this sentence.

2017-02-23 17:27 UTC, juliaelman commented on README.md
>  This repository hosts editable, open source design files of the [U.S. Web Design Standards](https://playbook.cio.gov/designstandards) for government designers or anyone wishing to make use of the UI
Let's update the url in this paragraph to https://standards.usa.gov

2017-02-23 18:17 UTC, juliasolorzano approved these changes

2017-02-23 18:17 UTC, merged

2017-02-23 18:17 UTC, juliaelman commented
Done 🚀